services:
  - type: web
    name: multiagent-llm-chess
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    # No environment variables needed for Ollama as it runs locally
